name: wheels

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_SKIP: cp36-*

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
